# Generated by Django 4.1 on 2022-09-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='averagerating',
            field=models.FloatField(default=0),
        ),
    ]
