# Generated by Django 4.1 on 2022-09-23 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='ratint',
            new_name='rating',
        ),
    ]
